# This file was generated by GoReleaser. DO NOT EDIT.
cask "openclue" do
  app "packaging/macos/OpenClue.app"

  caveats <<~EOS
    This software is provided under the Apache License 2.0, AS IS.
    Additional disclaimer terms are included with the package at:
      #{appdir}/OpenClue.app/Contents/Resources/Legal/RISK_NOTICE.txt
    You are solely responsible for your configuration, third-party components
    invoked by the software, and verifying any safety or security mechanisms.
    Not for high-risk or safety-critical use.
  EOS

  name "openclue"
  desc "OpenClue accelerates terminal workflows with deterministic, policy-first AI execution."
  homepage "https://openclue.ai"
  version "0.2.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oclue"
  binary "openclue"

  on_macos do
    on_intel do
      url "https://github.com/juangamnik/homebrew-openclue/releases/download/v#{version}/openclue_#{version}_darwin_amd64.zip",
        verified: "github.com/juangamnik/homebrew-openclue/"
      sha256 "0a2ed4e274fe0a2807db5475c4e265f9fc1b0bf1ffb59343b6714eab345dbfdc"
    end
    on_arm do
      url "https://github.com/juangamnik/homebrew-openclue/releases/download/v#{version}/openclue_#{version}_darwin_arm64.zip",
        verified: "github.com/juangamnik/homebrew-openclue/"
      sha256 "27edaca5e9db10c8d8bfb3002f3bb3263f6466bc73a014f2f06a95cd5fc7a075"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oclue"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openclue"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/packaging/macos/OpenClue.app"]
    end
  end

  # No zap stanza required
end
