# This file was generated by GoReleaser. DO NOT EDIT.
cask "openclue" do
  app "packaging/macos/OpenClue.app"

  caveats <<~EOS
    This software is provided under the Apache License 2.0, AS IS.
    Additional disclaimer terms are included with the package at:
      #{appdir}/OpenClue.app/Contents/Resources/Legal/RISK_NOTICE.txt
    You are solely responsible for your configuration, third-party components
    invoked by the software, and verifying any safety or security mechanisms.
    Not for high-risk or safety-critical use.
  EOS

  name "openclue"
  desc "OpenClue accelerates terminal workflows with deterministic, policy-first AI execution."
  homepage "https://openclue.ai"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "oclue"
  binary "openclue"

  on_macos do
    on_intel do
      url "https://github.com/juangamnik/homebrew-openclue/releases/download/v#{version}/openclue_#{version}_darwin_amd64.zip",
        verified: "github.com/juangamnik/homebrew-openclue/"
      sha256 "83582072183a3d737b675e45dd9132636177c39f7af67f5311c6ffb9955da775"
    end
    on_arm do
      url "https://github.com/juangamnik/homebrew-openclue/releases/download/v#{version}/openclue_#{version}_darwin_arm64.zip",
        verified: "github.com/juangamnik/homebrew-openclue/"
      sha256 "f93f0da2e93d2b10ff835e9e9adf235ad548a4fef1ac094ef71f501588a82c8c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/oclue"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/openclue"]
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/packaging/macos/OpenClue.app"]
    end
  end

  # No zap stanza required
end
